In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('df_train_2a.csv')
df_test = pd.read_csv('df_test_2a.csv')

In [133]:
# import os
# data_dir = './Task4_v2'
# activities = ['WALKING', 'WALKING_UPSTAIRS', 'WALKING_DOWNSTAIRS', 'STANDING', 'LAYING', 'SITTING']
# for acivity in activities:
#     print(acivity)
#     files = os.listdir(os.path.join(data_dir, acivity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, acivity, file), header=None, skiprows=1)
#         df_downsampled = df.groupby(np.arange(len(df)) // 2).mean()
#         index_50hz = np.linspace(0, len(df_downsampled) - 1, int(len(df_downsampled) * 4/5))
#         df_resampled_50hz = df_downsampled.reindex(index_50hz).interpolate(method='linear')
#         df_resampled_50hz.reset_index(drop=True, inplace=True)
#         df_resampled_50hz.to_csv(file, index=False)

#         start_idx = max(0, (len(df_resampled_50hz) - 500) // 2)
#         end_idx = start_idx + 500
#         df_final = df_resampled_50hz.iloc[start_idx:end_idx]
#         df_final.drop(columns=[0,4], inplace=True)

#         df_final.to_csv("./Tak4_v2_Trimmed"+ '/' + acivity + '/' + 'trimmed_'+ file, index=False, header=False)

In [6]:
df_train

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.848709,0.760164,0.736452,0.748299,0.782848,0.882488,0.958099,0.948714,0.930530,1.003035,...,1.353846,1.326801,1.187265,1.123056,1.044983,0.967130,0.955721,0.940260,0.937370,0.920635
1,0.994932,0.996157,0.997569,0.997141,0.997321,0.995469,0.992603,0.992008,0.996622,1.002989,...,0.996362,1.002647,1.001718,0.996088,0.993776,0.995001,0.995938,0.994459,0.993726,0.994293
2,1.029484,1.027762,1.025952,1.027855,1.029590,1.028772,1.028514,1.025848,1.022338,1.023719,...,1.031729,1.027246,1.023730,1.026660,1.031017,1.030908,1.028934,1.028393,1.028763,1.029616
3,0.873025,0.798615,0.727831,0.681650,0.624199,0.572181,0.627781,0.718508,0.835183,0.959438,...,0.555627,0.549743,0.622078,0.725444,0.821024,0.884565,1.006113,1.119521,1.068676,1.044513
4,0.782344,0.669613,0.622582,0.578245,0.551131,0.594676,0.689110,0.823618,0.891847,0.933120,...,0.581406,0.637681,0.662929,0.757451,0.920345,1.067191,1.129631,1.174664,1.338582,1.426424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,0.772641,0.759789,0.751038,0.879259,0.933638,1.028462,1.194758,1.314722,1.385784,1.293604,...,0.988027,0.980787,1.026476,1.049164,1.129574,1.233709,1.237486,1.244454,1.241550,1.188412
122,1.025773,1.025652,1.025421,1.026544,1.028941,1.028593,1.026072,1.024683,1.024759,1.024907,...,1.024350,1.024815,1.024743,1.025626,1.024969,1.024631,1.027661,1.030127,1.029474,1.027648
123,1.001754,1.005349,1.002868,1.000390,1.001920,0.997394,0.989835,0.983372,0.980548,0.983801,...,0.997297,0.995913,1.005183,1.022058,1.035586,1.039751,1.030010,1.012556,1.005530,1.007701
124,1.561116,1.512604,1.213361,0.817532,0.749051,0.965771,1.081938,1.111484,1.064656,0.918712,...,1.133274,1.158859,1.073613,1.032554,0.985686,0.892834,0.889423,0.865240,0.793612,0.743266
125,0.952782,0.958926,0.941394,0.972028,1.020612,1.035727,1.050725,1.061750,1.088724,1.132263,...,0.889219,0.895632,0.913397,0.933790,0.931520,0.915161,0.913009,0.933698,0.976148,1.008677

In [7]:
df_test

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,1.315677,1.604243,1.830893,1.898958,1.827327,1.620880,1.316908,1.170661,1.052928,0.754885,...,1.764761,1.639306,1.523885,1.416439,1.240125,1.087496,0.893483,0.738629,0.721044,0.631276
1,1.054856,1.136392,1.156623,1.144792,1.157303,1.256707,1.373923,1.357964,1.260566,1.143371,...,0.922238,0.988027,1.003726,1.025643,1.101458,1.162664,1.131585,1.101898,1.127893,1.159806
2,1.066860,1.057793,1.005084,0.953131,0.936750,0.894240,0.869101,0.777311,0.631513,0.622790,...,1.063830,1.100856,1.181338,1.254771,1.336512,1.414291,1.470916,1.593582,1.656637,1.481759
3,1.036042,1.036788,1.029928,1.022799,1.027641,1.036674,1.035558,1.031314,1.025582,1.022758,...,1.033032,1.029915,1.026137,1.028114,1.028717,1.029478,1.030757,1.028273,1.026989,1.028143
4,1.033301,1.032317,1.032423,1.033606,1.031874,1.029899,1.030803,1.033281,1.034185,1.032604,...,1.035920,1.030554,1.025169,1.030608,1.036265,1.037410,1.038579,1.038102,1.036806,1.033834
5,0.915502,0.954963,0.983694,1.020670,1.046503,1.132012,1.249839,1.310624,1.339386,1.351412,...,1.159150,1.206912,1.251561,1.272171,1.211178,1.108875,1.066814,1.081030,1.146494,1.268024
6,1.291127,1.297432,1.183386,1.182686,1.201565,1.195548,1.192607,1.127848,1.125313,1.278853,...,0.746054,0.790597,0.847483,0.906741,0.906648,0.857204,0.881844,0.903662,0.932606,1.017917
7,1.032340,1.032781,1.033193,1.036511,1.038426,1.027897,1.018963,1.023581,1.033635,1.043224,...,1.030667,1.034737,1.031542,1.023020,1.021244,1.024627,1.025150,1.025423,1.025224,1.024552
8,1.144170,1.248520,1.536808,1.810816,1.961262,1.612221,1.090601,0.832398,0.675541,0.690888,...,0.682072,0.956331,1.097197,1.077151,1.135742,1.157704,1.097518,1.124475,1.249014,1.362685
9,0.906851,0.892674,0.927821,0.876667,0.823696,0.768684,0.729186,0.782357,0.836134,0.904579,...,0.879559,0.846065,0.825003,0.847057,0.868695,0.907191,0.923909,0.939381,0.940602,0.933057
10,1.015275,1.002618,0.997276,0.998882,1.002961,1.002312,0.985065,0.964089,0.979620,1.006201,...,0.992090,0.989066,1.000204,1.013801,1.014127,1.003466,0.993694,0.991879,0.995322,0.995184
11,1.029188,1.032513,1.032401,1.030785,1.028962,1.029236,1.030266,1.028866,1.027575,1.026979,...,1.029208,1.027991,1.032222,1.036925,1.033528,1.028892,1.030731,1.032591,1.032081,1.033640
12,1.007989,1.008666,1.004921,1.000490,1.002042,1.008638,1.013399,1.014471,1.012399,1.006425,...,1.002568,1.005736,1.011433,1.014441,1.011348,1.006142,1.008772,1.012624,1.007923,1.004445
13,1.033779,1.036780,1.035747,1.033440,1.029783,1.029587,1.033593,1.032082,1.031942,1.035073,...,1.035200,1.035687,1.036201,1.034573,1.034619,1.034543,1.029746,1.026535,1.026324,1.029175
14,0.997028,0.997382,0.995781,0.997569,0.997430,0.996090,0.997757,0.995366,0.995933,0.998376,...,0.995341,0.992808,0.992914,0.994334,0.998938,0.995261,0.990426,0.992120,0.990685,0.988490
15,1.290181,1.340225,1.302615,1.281386,1.234988,1.170098,1.150358,1.171995,1.267013,1.367576,...,1.098861,1.138940,1.136407,1.130917,1.119326,1.143824,1.264135,1.446109,1.538821,1.152461
16,1.007194,1.011121,1.013975,1.015584,1.015046,1.013851,1.013883,1.015914,1.018434,1.019972,...,1.021275,1.022827,1.020953,1.016075,1.008814,1.004915,1.007997,1.012284,1.012109,1.006648
17,1.030318,1.030502,1.030696,1.030644,1.029482,1.027626,1.029128,1.030915,1.030387,1.033534,...,1.034664,1.034425,1.033431,1.032523,1.031949,1.033956,1.035290,1.031696,1.029284,1.030907
18,0.739666,0.727976,0.694355,0.726950,0.797370,0.831288,0.903037,0.977647,1.034314,1.053833,...,1.005586,0.919024,0.796550,0.719040,0.716453,0.714001,0.713732,0.719674,0.727900,0.790306
19,1.043811,1.045779,1.038616,1.029980,1.012584,1.006069,1.016572,1.018905,1.006505,0.998979,...,1.025632,1.024824,1.026196,1.027969,1.028582,1.027976,1.023876,1.021467,1.025295,1.029658
20,1.032408,1.033742,1.034543,1.033553,1.032413,1.032699,1.031476,1.031227,1.032369,1.033501,...,1.031615,1.030839,1.029907,1.029790,1.029825,1.030135,1.030165,1.029900,1.031256,1.032825
21,1.379732,1.556364,1.662228,1.703567,1.664493,1.547488,1.267446,1.167344,1.223358,1.097897,...,1.058965,1.165739,1.074440,1.109843,1.379316,1.547596,1.557898,1.507903,1.695931,1.873097
22,1.082104,1.200979,1.451168,1.709332,1.775582,1.734352,1.522744,1.257829,1.250166,1.296279,...,0.885365,1.091537,1.035172,1.013440,1.127905,1.082152,0.976065,0.834861,0.854847,0.971799
23,1.101109,1.210352,1.354673,1.457619,1.508252,1.528571,1.486989,1.432513,1.416955,1.367808,...,0.950121,0.827201,0.791985,0.719120,0.682602,0.713184,0.729197,0.814245,0.898585,0.991788
24,0.936093,0.979526,0.991082,1.023478,1.111923,1.221921,1.282912,1.264307,1.287447,1.308107,...,0.923876,0.708315,0.699095,0.903590,0.928439,0.869498,0.870246,0.826254,0.907089,0.962771
25,1.030106,1.028033,1.029675,1.030748,1.028459,1.026856,1.026550,1.027248,1.029322,1.032960,...,1.029660,1.030143,1.030497,1.028997,1.028353,1.026664,1.026900,1.029974,1.028981,1.028229
26,1.001716,0.997390,0.994945,0.993913,0.991768,0.991023,0.992098,0.990949,0.991036,0.994928,...,0.998123,0.996405,0.997234,0.997338,0.997027,1.000128,1.000702,0.999562,0.998329,0.995668
27,1.018722,1.017074,1.016951,1.018376,1.022782,1.024607,1.020334,1.018976,1.021007,1.023598,...,1.017747,1.019369,1.020573,1.020892,1.020331,1.020300,1.018808,1.018262,1.022079,1.024161
28,0.823841,0.836946,1.071590,1.471791,1.709201,1.631859,1.397959,1.200408,1.089309,1.121890,...,0.968896,1.054615,1.151727,1.231440,1.327370,1.447799,1.409123,1.155185,0.969121,0.931676
29,1.400996,1.442772,1.416238,1.385769,1.282461,1.162420,1.188707,1.229449,1.241575,1.305188,...,0.961534,1.029197,1.069965,1.109574,1.034696,0.930346,0.835514,0.746475,0.732622,0.720974
30,1.005598,1.008753,1.006595,1.005945,1.004864,1.002606,1.000730,1.002937,1.003774,1.003530,...,1.004585,1.003259,1.002130,1.001979,1.003649,1.002776,0.999983,0.999071,1.001185,1.005280
31,1.145927,1.223377,1.287581,1.337457,1.401695,1.475245,1.489430,1.438265,1.371391,1.286342,...,1.337721,1.372306,1.299840,1.185026,1.051910,0.927509,0.941579,0.984509,0.978359,0.982773
32,1.022061,1.019949,1.023432,1.030534,1.034457,1.032410,1.032238,1.033474,1.033092,1.037163,...,1.019259,1.018147,1.021644,1.022749,1.022270,1.021401,1.020334,1.020275,1.020468,1.020234
33,1.010339,1.011031,1.013025,1.012176,1.011595,1.014976,1.016340,1.012597,1.009065,1.009853,...,1.009384,1.006350,1.007670,1.009112,1.009975,1.011199,1.008918,1.007368,1.009801,1.010613
34,0.837400,0.950127,1.013442,0.996482,1.012600,0.992126,0.891540,0.842528,0.819883,0.852699,...,0.851235,0.760656,0.751069,0.749361,0.818099,1.067165,1.422500,1.664659,1.686888,1.849511
35,1.017370,1.020165,1.019453,1.016262,1.014875,1.012600,1.012187,1.012567,1.011243,1.012538,...,1.014396,1.016035,1.011499,1.009456,1.006829,1.005657,1.007690,1.011362,1.016674,1.017599
36,0.998095,0.995973,0.992344,0.993979,0.996056,0.997040,0.997717,0.999450,1.001817,1.001171,...,0.998457,1.005191,1.004134,1.002279,1.000625,0.998999,0.998388,0.995598,0.991592,0.992757
37,0.925585,1.072430,1.306935,1.558829,1.729902,1.691581,1.723449,1.684659,1.379212,1.108014,...,0.465390,0.526655,0.627260,0.731563,0.894509,0.975595,0.940932,1.140782,1.377008,1.523710
38,1.217164,1.319760,1.365283,1.643591,1.926625,1.715120,1.399297,1.107621,0.651709,0.728994,...,0.966358,1.054219,1.109556,0.990505,0.937853,0.975607,1.020856,1.198861,1.213602,1.175150
39,1.032328,1.032681,1.032851,1.029716,1.026087,1.028748,1.034167,1.036295,1.036381,1.035800,...,1.030841,1.031330,1.031456,1.030580,1.032790,1.033349,1.033220,1.034602,1.035476,1.035742
40,1.692685,2.052999,1.937325,1.749686,1.619644,1.476268,1.318844,1.078579,0.831149,0.751969,...,0.596812,0.653750,0.893707,1.094396,1.115332,0.972763,0.751223,0.542123,0.385830,0.398936
41,1.172154,1.183903,1.080747,1.029943,0.961082,0.882326,0.819033,0.739583,0.685461,0.685848,...,1.382691,1.391543,1.486226,1.483396,1.427703,1.359888,1.291690,1.270600,1.170076,1.024533
42,1.191643,1.313624,1.378930,1.271230,1.111157,1.012335,1.006189,1.197941,1.343679,1.334332,...,0.803562,0.859573,0.915230,0.912541,0.878447,0.918950,0.968843,1.024753,1.095481,1.122357
43,1.011422,1.011426,1.011220,1.011675,1.009088,1.004669,1.005591,1.007875,1.007755,1.007245,...,1.009124,1.009965,1.009079,1.009085,1.009743,1.008746,1.008517,1.009222,1.009826,1.011455
44,0.998463,0.996530,0.999737,1.002772,0.999512,0.999779,1.005743,1.008165,1.002082,0.994421,...,1.010615,1.010344,1.012706,1.016816,1.020912,1.022213,1.016820,1.012355,1.013827,1.012005
45,1.014923,1.013980,1.013337,1.015442,1.015216,1.013798,1.014901,1.014274,1.011932,1.012130,...,0.998727,1.001725,1.002828,0.999931,0.995384,0.996450,0.998702,0.997537,0.998601,1.001916
46,1.046037,1.051544,1.048978,1.043241,1.035898,1.031789,1.034878,1.035617,1.037460,1.041764,...,1.034893,1.035587,1.036598,1.032800,1.031275,1.032176,1.032519,1.033020,1.035219,1.038256
47,0.845016,0.855714,0.876904,0.923732,0.974971,1.000963,1.012456,1.019338,1.016773,1.010928,...,1.187885,1.215405,1.116048,0.940709,0.866824,0.946224,1.054302,1.076701,1.030516,0.980974
48,0.885406,0.916357,0.959665,0.895004,0.765785,0.779554,0.874024,0.957472,0.937730,0.851399,...,1.153904,1.294057,1.460310,1.677870,1.771225,1.592847,1.379184,1.328859,1.274880,1.151982
49,1.848986,1.960485,1.699150,1.502177,1.307030,1.207614,1.100566,0.901439,0.957394,0.866803,...,0.734663,0.634799,0.494327,0.436825,0.423448,0.396129,0.455363,0.595924,0.805031,0.953517
50,0.736993,0.665065,0.552809,0.489626,0.474678,0.496547,0.563221,0.695304,0.864325,1.001807,...,1.013566,1.007004,0.975709,0.968537,0.954030,0.871968,0.857605,0.832102,0.749023,0.705472
51,1.013725,1.016844,1.016654,1.012315,1.011428,1.010976,1.012668,1.012599,1.009748,1.010564,...,1.014009,1.015418,1.016323,1.016289,1.014158,1.013529,1.015243,1.016043,1.016794,1.015516
52,1.029237,1.012415,0.943922,1.005528,0.961418,0.934399,0.912760,0.801370,0.778527,0.745577,...,0.785263,0.754626,0.770267,0.801376,0.858630,0.883603,0.870729,0.889926,0.943849,1.026482
53,1.019295,1.017199,1.020572,1.022085,1.022448,1.024382,1.023603,1.022600,1.021518,1.019774,...,1.023272,1.019372,1.018486,1.020751,1.022034,1.022290,1.022840,1.021040,1.018116,1.019601

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [9]:
from MakeDataset import y_train, y_test

Training data shape:  (126, 500, 3)
Testing data shape:  (54, 500, 3)

In [10]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(df_train, y_train)

DecisionTreeClassifier(random_state=42)

In [11]:
y_pred = clf.predict(df_test)

# Calculate accuracy, precision, recall, confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.50
Precision: 0.48
Recall: 0.50
Confusion Matrix:
[[4 3 1 0 0 1]
 [4 2 2 0 1 0]
 [6 2 1 0 0 0]
 [0 0 0 6 2 1]
 [0 0 0 2 7 0]
 [0 0 0 2 0 7]]

In [12]:
# sriv_laying1 = pd.read_csv('Task4/Laying/trimmed_Sriv_1.csv', header=None)

In [13]:
# sriv_laying1.drop(columns=[0,4], inplace=True)

In [14]:
# import os
# activities = ['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING DOWNSTAIRS', 'WALKING UPSTAIRS']
# data_dir = './Task4'
# for activity in activities:
#     print(activity)
#     files = os.listdir(os.path.join(data_dir, activity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, activity, file), header=None)
#         df.drop(columns=[0,4], inplace=True)
#         df.to_csv("./Task4"+ '/' + activity + '/' + 'trimmed_'+ file, index=False,header=False)

In [15]:
# import os
# activities = ['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING DOWNSTAIRS', 'WALKING UPSTAIRS']
# data_dir = './Task4'
# for activity in activities:
#     print(activity)
#     files = os.listdir(os.path.join(data_dir, activity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, activity, file), header=None)
#         print(df.shape)
#         break

In [16]:
from MakeDataset_Linear import X, y
import pandas as pd

print(X.shape, y.shape)

(36, 500, 3) (36,)

In [17]:
X_train_list = []
X_test_list = []

for i in range(0, 36, 6):
    X_train_list.append(X[i:i + 4, :, :])  # First 4 go to X_train
    X_test_list.append(X[i + 4:i + 6, :, :])  # Next 2 go to X_test

X_train_new = np.concatenate(X_train_list, axis=0)
X_test_new = np.concatenate(X_test_list, axis=0)

print(f'X_train_new shape: {X_train_new.shape}')
print(f'X_test_new shape: {X_test_new.shape}')

X_train_new shape: (24, 500, 3)
X_test_new shape: (12, 500, 3)

In [18]:
y_train_list = []
y_test_list = []

for i in range(0, len(y), 6):
    y_train_list.append(y[i:i + 4])  # First 4 go to y_train
    y_test_list.append(y[i + 4:i + 6])  # Next 2 go to y_test

y_train_new = np.concatenate(y_train_list, axis=0)
y_test_new = np.concatenate(y_test_list, axis=0)

print(f'y_train_new: {y_train_new}')
print(f'y_test_new: {y_test_new}')

y_train_new: [6 6 6 6 4 4 4 4 5 5 5 5 1 1 1 1 3 3 3 3 2 2 2 2]
y_test_new: [6 6 4 4 5 5 1 1 3 3 2 2]

In [19]:
X_norm = np.linalg.norm(X, axis=2)
X_norm.shape

(36, 500)

In [20]:
from MakeDataset import X_train, y_train, X_test, y_test

In [21]:
df_raw_train = pd.read_csv('df_train_2a.csv')

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

clf = DecisionTreeClassifier(random_state=42)
clf.fit(df_raw_train.values, y_train)
y_pred = clf.predict(X_norm)
print("Accuracy for raw data: ", accuracy_score(y_pred, y))

Accuracy for raw data:  0.1388888888888889

In [25]:
import tsfel
import pandas as pd

cfg = tsfel.get_features_by_domain()
tsfel_X = tsfel.time_series_features_extractor(cfg, X)

print(tsfel_X.shape)

/tmp/ipykernel_173429/1426764846.py:5: UserWarning: Using default sampling frequency set in configuration file.
  tsfel_X = tsfel.time_series_features_extractor(cfg, X)

/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(

(36, 495)

In [26]:
tsfel_X_train = pd.read_csv('tsfel_x_train.csv')

In [27]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(tsfel_X_train.values, y_train)
y_pred = clf.predict(tsfel_X.values)
print("Accuracy for TSFEL data: ", accuracy_score(y_pred, y))

Accuracy for TSFEL data:  0.2222222222222222

2. Use the data you collected to predict the activities that you performed. Decide whether to apply preprocessing and featurization, and if so, choose the appropriate methods. How did the model perform? [1 marks]

In [28]:
X_train_new.shape

(24, 500, 3)

In [29]:
X_train_new_norm = np.linalg.norm(X_train_new, axis=2)
X_test_new_norm = np.linalg.norm(X_test_new, axis=2)
print(X_train_new_norm.shape, X_test_new_norm.shape)

(24, 500) (12, 500)

In [30]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train_new_norm, y_train_new)
y_pred = clf.predict(X_test_new_norm)
print("Accuracy for our data: ", accuracy_score(y_pred, y_test_new))

Accuracy for our data:  0.5833333333333334